headers: &headers
  - Accept
  - Authorization
bat-qa:
  service: bat-cdn-qa
  headers: *headers
  domain:
    - qa.find-postgraduate-teacher-training.service.gov.uk
    - qa.register-trainee-teachers.education.gov.uk
    - qa.api.publish-teacher-training-courses.service.gov.uk
    - qa.publish-teacher-training-courses.service.gov.uk
    - audit.register-trainee-teachers.education.gov.uk
    - qa.apply-for-teacher-training.service.gov.uk
bat-staging:
  service: bat-cdn-staging
  headers: *headers
  domain:
    - staging.find-postgraduate-teacher-training.service.gov.uk
    - staging.register-trainee-teachers.education.gov.uk
    - staging.api.publish-teacher-training-courses.service.gov.uk
    - staging.publish-teacher-training-courses.service.gov.uk
    - staging.apply-for-teacher-training.service.gov.uk

git-staging:
  service: get-into-teaching-cdn-test
  headers: *headers
  domain:
    - staging-adviser-getintoteaching.education.gov.uk
    - staging-getintoteaching.education.gov.uk
bat-prod:
  service: bat-cdn-prod
  headers: *headers
  domain:
    - www2.find-postgraduate-teacher-training.service.gov.uk
    - www.find-postgraduate-teacher-training.service.gov.uk
    - www.register-trainee-teachers.education.gov.uk
    - sandbox.find-postgraduate-teacher-training.service.gov.uk
    - sandbox.api.publish-teacher-training-courses.service.gov.uk
    - sandbox.publish-teacher-training-courses.service.gov.uk
    - sandbox.register-trainee-teachers.education.gov.uk
    - sandbox.apply-for-teacher-training.service.gov.uk
    - www.apply-for-teacher-training.service.gov.uk
    - www.publish-teacher-training-courses.service.gov.uk

git-prod:
  service: get-into-teaching-cdn-prod
  headers: *headers
  domain:
    - adviser-getintoteaching.education.gov.uk
    - beta-adviser-getintoteaching.education.gov.uk
    - getintoteaching.education.gov.uk
    - beta-getintoteaching.education.gov.uk

